# Exercise 2.A Fundamentals of pandas

# Import Libraries

In [157]:
import numpy as np
import pandas as pd

# Imported NumPy and pandas for data analysis work

# Series
# Create Python objects

In [158]:
aa = [1, 2, 3, 4]
ab = (5, 6, 7, 8)
ac = {9, 10, 11, 12}
ad = {'first': 13, 'second': 14, 'third': 15, 'fourth': 16}

ser1 = pd.Series(aa)
ser2 = pd.Series(ab)
ser3 = pd.Series(list(ac))
ser4 = pd.Series(ad)

print(ser1)
print(ser2)
print(ser3)
print(ser4)

# TypeError: Series() takes at most 2 positional arguments (4 given)
# This happens because multiple values must be passed as a list or array

0    1
1    2
2    3
3    4
dtype: int64
0    5
1    6
2    7
3    8
dtype: int64
0     9
1    10
2    11
3    12
dtype: int64
first     13
second    14
third     15
fourth    16
dtype: int64

# TypeError example

In [154]:
ser5 = pd.Series(17, 18, 19, 20)


# TypeError:
# Series.__init__() takes from 1 to 4 positional arguments but 5 were given

TypeError: Index(...) must be called with a collection of some kind, 18 was passed

# DataFrames from Series
# Create DataFrame from ser1

In [159]:
df1 = pd.DataFrame(ser1)
df1.insert(1, "col2", ser2)
df1.insert(2, "col3", ser3)
df1["col4"] = ser4

df1["col4"] = ser4

# This may produce NaN values because ser4 uses dictionary keys
# while df1 uses numeric indexing
df1

   0  col2  col3  col4
0  1     5     9   NaN
1  2     6    10   NaN
2  3     7    11   NaN
3  4     8    12   NaN

# Add columns using insert()

In [160]:

df1.loc[4] = [5, 9, 12, 0]
df1

# Add columns using insert()

   0  col2  col3  col4
0  1     5     9   NaN
1  2     6    10   NaN
2  3     7    11   NaN
3  4     8    12   NaN
4  5     9    12   0.0

# Add column using ser4

In [163]:
df1["col4"] = ser4

df1

# ser4 is a dictionary-based Series, so alignment by index affects output
# missing or misaligned values may appear as NaN

   0  col2  col3  col4
0  1     5     9   NaN
1  2     6    10   NaN
2  3     7    11   NaN
3  4     8    12   NaN
4  5     9    12   NaN

# Add new row

In [162]:
df1.loc[4] = [5, 9, 12, 0]

df1

# Added a new row using .loc indexing

   0  col2  col3  col4
0  1     5     9   NaN
1  2     6    10   NaN
2  3     7    11   NaN
3  4     8    12   NaN
4  5     9    12   0.0

# Reading Data into a DataFrame
# Load sakila dataset

In [149]:
import os
os.getcwd()

'/Users/eyerusalemdebero/Documents/DataAnalytics/week-07/Module 2 pandas'

In [164]:
df2 = pd.read_csv("sakila_example.csv")
df2

,title,description,category,language,actor_name
0,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,PENELOPE GUINESS
1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,CHRISTIAN GABLE
2,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,LUCILLE TRACY
3,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,SANDRA PECK
4,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,JOHNNY CAGE
...,...,...,...,...,...
257,ATTRACTION NEWTON,A Astounding Panorama of a Composer And a Fris...,New,English,GARY PENN
258,ATTRACTION NEWTON,A Astounding Panorama of a Composer And a Fris...,New,English,CHRISTOPHER WEST
259,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,DUSTIN TAUTOU
260,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,ANGELA HUDSON
261,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,JAMES PITT

In [165]:
df2 = pd.read_csv("/Users/eyerusalemdebero/Documents/DataAnalytics/week-07/Module 2 pandas/sakila_example.csv")
df2

,title,description,category,language,actor_name
0,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,PENELOPE GUINESS
1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,CHRISTIAN GABLE
2,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,LUCILLE TRACY
3,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,SANDRA PECK
4,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,JOHNNY CAGE
...,...,...,...,...,...
257,ATTRACTION NEWTON,A Astounding Panorama of a Composer And a Fris...,New,English,GARY PENN
258,ATTRACTION NEWTON,A Astounding Panorama of a Composer And a Fris...,New,English,CHRISTOPHER WEST
259,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,DUSTIN TAUTOU
260,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,ANGELA HUDSON
261,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,JAMES PITT

In [166]:
# Reading Data into a DataFrame
# Load sakila dataset

df2 = pd.read_csv('sakila_example.csv')

df2

print(df2.head())

              title                                        description  \
0  ACADEMY DINOSAUR  A Epic Drama of a Feminist And a Mad Scientist...
1  ACADEMY DINOSAUR  A Epic Drama of a Feminist And a Mad Scientist...
2  ACADEMY DINOSAUR  A Epic Drama of a Feminist And a Mad Scientist...
3  ACADEMY DINOSAUR  A Epic Drama of a Feminist And a Mad Scientist...
4  ACADEMY DINOSAUR  A Epic Drama of a Feminist And a Mad Scientist...

      category language        actor_name
0  Documentary  English  PENELOPE GUINESS
1  Documentary  English   CHRISTIAN GABLE
2  Documentary  English     LUCILLE TRACY
3  Documentary  English       SANDRA PECK
4  Documentary  English       JOHNNY CAGE

# Top 5 rows

In [167]:
# Display top 5 rows
df2.head()

,title,description,category,language,actor_name
0,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,PENELOPE GUINESS
1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,CHRISTIAN GABLE
2,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,LUCILLE TRACY
3,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,SANDRA PECK
4,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,JOHNNY CAGE

# Last 10 rows

In [168]:
df2.tail(10)

,title,description,category,language,actor_name
252,ATTACKS HATE,A Fast-Paced Panorama of a Technical Writer An...,Sci-Fi,English,MILLA KEITEL
253,ATTACKS HATE,A Fast-Paced Panorama of a Technical Writer An...,Sci-Fi,English,GROUCHO DUNST
254,ATTACKS HATE,A Fast-Paced Panorama of a Technical Writer An...,Sci-Fi,English,BURT TEMPLE
255,ATTRACTION NEWTON,A Astounding Panorama of a Composer And a Fris...,New,English,UMA WOOD
256,ATTRACTION NEWTON,A Astounding Panorama of a Composer And a Fris...,New,English,RIP WINSLET
257,ATTRACTION NEWTON,A Astounding Panorama of a Composer And a Fris...,New,English,GARY PENN
258,ATTRACTION NEWTON,A Astounding Panorama of a Composer And a Fris...,New,English,CHRISTOPHER WEST
259,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,DUSTIN TAUTOU
260,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,ANGELA HUDSON
261,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,JAMES PITT

# Info

In [169]:
df2.info()

# Shows column names, data types, and missing values

<class 'pandas.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        262 non-null    str
 1   description  262 non-null    str
 2   category     262 non-null    str
 3   language     262 non-null    str
 4   actor_name   262 non-null    str
dtypes: str(5)
memory usage: 10.4 KB

# Describe

In [170]:
df2.describe()

# Shows statistical summary for numeric columns

,title,description,category,language,actor_name
count,262,262,262,262,262
unique,46,46,15,1,145
top,ARABIA DOGMA,A Touching Epistle of a Madman And a Mad Cow w...,Horror,English,OPRAH KILMER
freq,12,12,55,262,8

# Load northwind dataset

In [173]:
df3 = pd.read_csv("/Users/eyerusalemdebero/Documents/DataAnalytics/week-07/Module 2 pandas/northwind_example.csv")
df3

# Loaded second dataset for comparison

     OrderID                    ProductName  UnitPrice  Quantity
0      10248                 Queso Cabrales       14.0        12
1      10248  Singaporean Hokkien Fried Mee        9.8        10
2      10248         Mozzarella di Giovanni       34.8         5
3      10249          Manjimup Dried Apples       42.4        40
4      10249                           Tofu       18.6         9
..       ...                            ...        ...       ...
495    10435         Mozzarella di Giovanni       27.8        10
496    10436         Gnocchi di nonna Alice       30.4        40
497    10436       Wimmers gute Semmelkndel       26.6        30
498    10436             Rhnbru Klosterbier        6.2        24
499    10436                      Spegesild        9.6         5

[500 rows x 4 columns]

# Describe df3

In [174]:
df3.describe()

# Shows statistical summary of numeric columns in df3
# Results differ based on dataset structure and column types

            OrderID   UnitPrice    Quantity
count    500.000000  500.000000  500.000000
mean   10341.364000   23.371400   24.330000
std       54.442663   27.334436   18.069702
min    10248.000000    2.000000    1.000000
25%    10294.000000   10.400000   10.000000
50%    10341.000000   15.800000   20.000000
75%    10389.000000   27.800000   32.000000
max    10436.000000  210.800000  120.000000

# Insights from df3
- Includes numeric statistics (mean, std, quartiles)
- Useful because data is numeric
- Different from df2 because df2 is categorical text data

# Coding a DataFrame
# Create dictionary

In [175]:
test_data = {
    'ID': [1, 2, 3, 4, 5, 6, 7, 8],
    'Name': ['Alicia', 'Bob', 'Charlie', 'Dominic', 'Eve', 'Frank', 'Grace', 'Heidi'],
    'Age': [25, np.nan, 22, 19, 31, 35, np.nan, 18],
    'City': ['NY', 'LA', 'Chicago', 'Houston', 'Phoenix', 'Boston', 'Austin', 'San Diego'],
    'Score': [85, 92, -1, 65, 78, np.nan, 55, 90]
}


# Created dataset with missing values and mixed data types

# Create DataFrame

In [176]:
df4 = pd.DataFrame(test_data)

df4

# Converted dictionary into pandas DataFrame

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
2   3  Charlie  22.0    Chicago   -1.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [180]:
# Create df4

df4 = pd.DataFrame(test_data)
df4

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
2   3  Charlie  22.0    Chicago   -1.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

# Export to CSV

In [177]:
df4.to_csv("test_data.csv", index=False)

# Exported DataFrame to CSV file without index column