# Import Libraries

In [ ]:
import numpy as np
import pandas as pd

# Imported NumPy and pandas for data cleaning tasks

# Load Dataset

In [ ]:
df = pd.read_csv("test_data.csv")
df

# Loaded test_data.csv into a DataFrame

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
2   3  Charlie  22.0    Chicago   -1.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

# Data Summary

In [17]:
df.describe()

# Shows statistical summary of numeric columns (Age, Score, etc.)

            ID       Age      Score
count  8.00000   6.00000   7.000000
mean   4.50000  25.00000  66.285714
std    2.44949   6.78233  32.576650
min    1.00000  18.00000  -1.000000
25%    2.75000  19.75000  60.000000
50%    4.50000  23.50000  78.000000
75%    6.25000  29.50000  87.500000
max    8.00000  35.00000  92.000000

# Filtering a DataFrame
# Age greater than 18

In [18]:
df[df["Age"] > 18]

# Filters rows where Age is greater than 18

   ID     Name   Age     City  Score
0   1   Alicia  25.0       NY   85.0
2   3  Charlie  22.0  Chicago   -1.0
3   4  Dominic  19.0  Houston   65.0
4   5      Eve  31.0  Phoenix   78.0
5   6    Frank  35.0   Boston    NaN

# Score between 50 and 100

In [19]:
df[(df["Score"] > 50) & (df["Score"] < 100)]

# Filters rows where Score is between 50 and 100

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

# Modifying a DataFrame
# Remove invalid scores

In [20]:
df_cleaned = df[df["Score"] >= 0]
df_cleaned


# Removed rows where Score is less than 0 (invalid data)

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

# Fill missing Age values

In [21]:
df_cleaned["Age"] = df_cleaned["Age"].fillna(df_cleaned["Age"].mean())
df_cleaned

# Replaced missing Age values with mean Age

   ID     Name    Age       City  Score
0   1   Alicia  25.00         NY   85.0
1   2      Bob  23.25         LA   92.0
3   4  Dominic  19.00    Houston   65.0
4   5      Eve  31.00    Phoenix   78.0
6   7    Grace  23.25     Austin   55.0
7   8    Heidi  18.00  San Diego   90.0

# Replace Score value of 0 with mean

In [22]:
df_cleaned["Score"] = df_cleaned["Score"].replace(
    0,
    df_cleaned["Score"].mean()
)
df_cleaned

# Replaced Score value of 0 with average Score

   ID     Name    Age       City  Score
0   1   Alicia  25.00         NY   85.0
1   2      Bob  23.25         LA   92.0
3   4  Dominic  19.00    Houston   65.0
4   5      Eve  31.00    Phoenix   78.0
6   7    Grace  23.25     Austin   55.0
7   8    Heidi  18.00  San Diego   90.0

# Drop remaining NaN values

In [23]:
df_cleaned = df_cleaned.dropna()
df_cleaned

# Removed any remaining missing values

   ID     Name    Age       City  Score
0   1   Alicia  25.00         NY   85.0
1   2      Bob  23.25         LA   92.0
3   4  Dominic  19.00    Houston   65.0
4   5      Eve  31.00    Phoenix   78.0
6   7    Grace  23.25     Austin   55.0
7   8    Heidi  18.00  San Diego   90.0

# Set ID as index and drop column

In [24]:
df_cleaned = df_cleaned.set_index("ID")
df_cleaned

# Set ID as index and removed ID column from DataFrame

       Name    Age       City  Score
ID
1    Alicia  25.00         NY   85.0
2       Bob  23.25         LA   92.0
4   Dominic  19.00    Houston   65.0
5       Eve  31.00    Phoenix   78.0
7     Grace  23.25     Austin   55.0
8     Heidi  18.00  San Diego   90.0